# First draft
It is just working!

# To Do

 - clean the code
 - explain the code step by step
 - optimize the implementation
 - add plots
 - make it work on data format from Kaggle
 - make it work on any rating data
 

In [1]:
"""   Collaborative filtering algorithm to predict user ratings for films, based on previous ratings in netflix dataset
 ---  2018, AliSaaalehi@gmail.com 
 ---  subset of Netflix dataset is used. Look at the "description.txt" for more info on dataset
 """

import csv
import time 
import math
import pdb
import numpy as np
import random as rnd
import matplotlib.pyplot as plt

In [14]:
# utility functions


def show_statistics(users_movies, plot_flag=False, reshape_flag=True):
    # this fuction shows some information about the users_movies matrix
    
    print("Shape of the users_movies matrix: ", users_movies.shape)
    zero_num=users_movies.size - np.count_nonzero(users_movies)
    
    print("Number of zero element of the matrix: ", zero_num)
    print("Sparsness of the matrix: ", (float(zero_num) / users_movies.size)*100)

    # reshape and plot the matrix like an image
    if plot_flag== True:
        if reshape_flag==True:
            plt.imshow(users_movies.reshape(1632,1633))
        else:
            plt.imshow(users_movies)
        plt.colorbar()
        plt.title("Reshaped version of user-movie matrix")
        plt.show()

In [3]:
# Read ratings.txt 

with open('./netflix/ratings.txt', 'r') as file_handle:
    data_reader = csv.reader(file_handle, delimiter=',')
    ratings = []
    for row in data_reader:
        ratings.append(list(map(float,row)))
ratings=np.asarray(ratings)

In [5]:
# Read movie_titles.txt 

with open('./netflix/movie_titles.txt', 'r') as file_handle: # , encoding ='ISO-8859-1'
    data_reader = csv.reader(file_handle, delimiter=',')
    movie_titles_dict = dict()
    for row in data_reader:
        year_descript = [row[1]]
        year_descript.append(row[2])
        movie_titles_dict [float(row[0])] = year_descript


In [6]:
# shuffle the dataset before doing anything 

np.random.shuffle(ratings)

In [7]:
#create a dictionary to map user ids to indexes

user_unique=np.unique(ratings[:,1])
users_num=user_unique.size
users_d={x:y for x,y in zip(user_unique,range(users_num))} # user dictionary

In [8]:
# create a dictionary to map movie ids to indexes
movie_unique=np.unique(ratings[:,0])
movies_num=movie_unique.size
movies_d={x:y for x,y in zip(movie_unique,range(movies_num))} # movie dictionary

In [10]:
# separate test and traind data
# be careful, dictionaries should be created before separating test and train!

ratings_num=(ratings.shape)[0]
#print(ratings_num)

test_num= int(math.floor(0.1*ratings_num/100))
print(test_num)

test_ratings=ratings[0:test_num,:]
#print(test_ratings[0:10,:])

train_ratings=ratings[test_num+1:-1,:]
#print(train_ratings.shape)


227


In [15]:
# creat users-movies matrix
users_movies=np.zeros((users_num,movies_num),dtype=int)

for row in train_ratings:
    m_index=movies_d[row[0]]
    u_index=users_d[row[1]]
    users_movies[u_index,m_index]=row[2]

show_statistics(users_movies, plot_flag=False, reshape_flag=True)

('Shape of the users_movies matrix: ', (28968, 92))
('Number of zero element of the matrix: ', 2437512)
('Sparsness of the matrix: ', 91.46194301358021)


In [18]:
# mesaure averag

users_sum_ratings = np.sum(users_movies, axis=1)
nonzero_nums= np.count_nonzero(users_movies, axis=1)
users_avg_ratings = np.zeros(users_sum_ratings.shape, dtype=float)

# to avoid division by zero
#proper_inds = nonzero_nums>0
for i in range(users_sum_ratings.size):
    if nonzero_nums[i]!=0:
        users_avg_ratings[i] = users_sum_ratings[i] / nonzero_nums[i]
        
print("Number of users with zero average ratings: " , users_avg_ratings.size - np.count_nonzero(users_avg_ratings))
s=-10
e=-1
print(users_sum_ratings[s:e])
print(nonzero_nums[s:e])
print(users_avg_ratings[s:e])
#plt.imshow(users_avg_ratings[0:28900].reshape(170,170))
#plt.colorbar()
#plt.show()

('Number of users with zero average ratings: ', 0)
[14 24 33 18 20 20 37 20 19]
[4 8 9 5 8 6 9 5 6]
[3. 3. 3. 3. 2. 3. 4. 4. 3.]


In [19]:
#Normalize rates by the users average weight

print (users_movies[1,:])

non_zero_um= np.zeros(users_movies.shape, dtype=int)
non_zero_um[users_movies>0]=1

users_movies_normalized = np.subtract(users_movies,users_avg_ratings[:,None])
users_movies_normalized = np.multiply(users_movies_normalized,non_zero_um)


[0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 4 0 0 0 0 0 0 3 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0
 0 0 0 0 0 0 3 5 0 0 0 0 0 4 0 0 0 0]


In [20]:
tic = time.time()
# form a matrix containing the number of common movies between users
common_matrix=np.matmul(non_zero_um , non_zero_um.T)

print("processing time: ", time.time()-tic)

('processing time: ', 54.82439684867859)


In [21]:
def predict_rating(user_index, movie_index, min_common_movies=2):
     
    # Look at the row of the common_matrix which shows number of common movies between this user and all other users in the dataset
    # Then filter those that have more than specific number of common movies rated
    common_row = common_matrix [user_index,:]
    similar_users= (np.where( common_row > min_common_movies))[0] # The function np.Where() returns results in the form of tuple, we need the
                                                      #  list of indexes which in in the first lement of that tuple
    
    active_user_ratings = users_movies_normalized [user_index,:] # Remember these are normalized ratings, we do not need to subtract average to normalize them
    
    number_of_similar_users = similar_users.size
    similarity_list = np.zeros((number_of_similar_users,1), dtype=float) # Empty list to store similarity measures (all w(a,i) from equation (2))
    
    if (number_of_similar_users == 0):
        print ('No smilar user in the dataset found! ')
        print ('Averge rating for the user is returned! ')
        predicted_rate = users_avg_ratings[user_index]
        return predicted_rate
    
   
    for i in range(number_of_similar_users):
        current_similar_user_index = similar_users [i]
        current_similar_user_ratings = users_movies_normalized [current_similar_user_index,:]

        # Numinator of the equation (2): sum of product of active users normalized rating with all similar users
        numinator= np.matmul(active_user_ratings.T , current_similar_user_ratings)
        
        # Denominator part: To avoid foor loops I will using logical operations
        number_of_movies = active_user_ratings.size
        denuminator_1 = 0
        denuminator_2 = 0

        for j in range(number_of_movies):
            if active_user_ratings[j] !=0 and current_similar_user_ratings[j] !=0:
                denuminator_1 += (active_user_ratings[j] **2)
                denuminator_2 += (current_similar_user_ratings[j] **2)
        denuminator = math.sqrt(denuminator_1 * denuminator_2)

        # Avoid division
        if denuminator == 0:
            similarity_list[i] = 0
        else:
            similarity_list[i] = numinator / denuminator      
        
    
    # Finally sum up every thing and mesure predicted rate
    sigma_part = 0
    for i in range(number_of_similar_users):
        current_similar_user_index = similar_users [i]
        sigma_part = users_movies_normalized [current_similar_user_index, movie_index] * similarity_list[i]
    
    
    normalization_factor = np.sum(np.absolute(similarity_list))
    predicted_rate= users_avg_ratings[user_index]
    
    if normalization_factor !=0:
        predicted_rate +=  sigma_part / normalization_factor
        
    # Finall sanity checks (This will not happen hopefully)
    if predicted_rate > 5: 
        predicted_rate = 5 
    elif predicted_rate < 0:
        predicted_rate = 0
    
    return predicted_rate

In [22]:
error = 0
num = 5
for r in range(num):

    row = test_ratings[r,:]
    movie_id = movies_d[row[0]]
    test_user_id = users_d[row[1]]
    real_rate=row[2]
    predicted_rate = predict_rating(test_user_id, movie_id, min_common_movies = 0)
    print('--------------------------------------------------')
    print('user r: ',r,'   Predicted Rate=' + str(predicted_rate))
    print('             Real rate= '+ str(real_rate))
    error += (predicted_rate - real_rate) ** 2


print ('MSE: ', error / num)

--------------------------------------------------
('user r: ', 0, '   Predicted Rate=[3.00001905]')
             Real rate= 2.0
--------------------------------------------------
('user r: ', 1, '   Predicted Rate=[2.]')
             Real rate= 3.0
--------------------------------------------------
('user r: ', 2, '   Predicted Rate=[4.]')
             Real rate= 4.0
--------------------------------------------------
('user r: ', 3, '   Predicted Rate=[4.00005535]')
             Real rate= 5.0
--------------------------------------------------
('user r: ', 4, '   Predicted Rate=[2.]')
             Real rate= 4.0
('MSE: ', array([1.39998548]))


In [23]:
while True:
    
    quary_user_id = 160977
    quary_year= '2004'

    quary_user_id =  int(input('Enter a valid user id: '))
    quary_year = input ('Enter the desired year: ')

    min_rate_threshold = 3
    test_user_index = users_d[quary_user_id]
    print ('*** Recommended movies ***')
    for m in movie_unique:
        movie_index = movies_d[m]
        #print (movie_titles_dict[m][0])

        if  users_movies[test_user_index, movie_index]==0 and movie_titles_dict[m][0] == quary_year:
            predicted_rate = predict_rating(test_user_id, movie_id, min_common_movies = 2)
            if predicted_rate >= min_rate_threshold:
                print(movie_titles_dict[m][1])
    print ('*** ------------------ ***')
    
    if input('press q to exit or anything to try again')=='q':
        break

Enter a valid user id: 160977
Enter the desired year: 2011
*** Recommended movies ***
*** ------------------ ***
press q to exit or anything to try againq


NameError: name 'q' is not defined

# Reference

“Empirical analysis of Predictive Algorithms for Collaborative Filtering by John S. Breese et al. 1998”